### ISSUE TITLE
针对同一个NineGridImageView对它多次赋值报错了

### ISSUE THREAD

**Issue by WaylanPunch** [laobie/NineGridImageView#6]
打了几行日志：

```
public void setImagesData(List lists) {
        try {
            if (lists == null || lists.isEmpty()) {
                LogUtil.d(TAG, "setImagesData debug, New List = NULL");
                this.setVisibility(GONE);
                return;
            } else {
                LogUtil.d(TAG, "setImagesData debug, New List != NULL, Size = " + lists.size());
                this.setVisibility(VISIBLE);
            }
            LogUtil.d(TAG, "setImagesData debug, Max Size = " + mMaxSize);
            if (mMaxSize > 0 && lists.size() > mMaxSize) {
                lists = lists.subList(0, mMaxSize);
            }
            LogUtil.d(TAG, "setImagesData debug, Show Style = " + mShowStyle);
            int[] gridParam = calculateGridParam(lists.size(), mShowStyle);
            mRowCount = gridParam[0];
            mColumnCount = gridParam[1];
            LogUtil.d(TAG, "setImagesData debug, Row Count = " + mRowCount);
            LogUtil.d(TAG, "setImagesData debug, Column Count = " + mColumnCount);
            if (mImgDataList == null) {
                LogUtil.d(TAG, "setImagesData debug, Old List = NULL");
                int i = 0;
                while (i < lists.size()) {
                    GFImageView iv = getImageView(i);
                    if (iv == null) {
                        return;
                    }
                    addView(iv, generateDefaultLayoutParams());
                    i++;
                }
            } else {
                LogUtil.d(TAG, "setImagesData debug, Old List != NULL");
                int oldViewCount = mImgDataList.size();
                int newViewCount = lists.size();
                if (oldViewCount > newViewCount) {
                    removeViews(newViewCount, oldViewCount - newViewCount);
                } else if (oldViewCount < newViewCount) {
                    for (int i = oldViewCount; i < newViewCount; i++) {
                        GFImageView iv = getImageView(i);
                        if (iv == null) {
                            return;
                        }
                        addView(iv, generateDefaultLayoutParams());
                    }
                }
            }
            mImgDataList = lists;
            requestLayout();
        } catch (Exception e) {
            LogUtil.e(TAG, "setImagesData error", e);
        }
    }
```

日志输出如下：

```
04-18 20:56:51.837 19831-19831/NineGridImageView: setImagesData debug, New List != NULL, Size = 6
04-18 20:56:51.837 19831-19831/NineGridImageView: setImagesData debug, Max Size = 9
04-18 20:56:51.837 19831-19831/NineGridImageView: setImagesData debug, Show Style = 1
04-18 20:56:51.837 19831-19831/NineGridImageView: setImagesData debug, Row Count = 2
04-18 20:56:51.837 19831-19831/NineGridImageView: setImagesData debug, Column Count = 3
04-18 20:56:51.837 19831-19831/NineGridImageView: setImagesData debug, Old List != NULL
04-18 20:56:51.838 19831-19831/NineGridImageView: setImagesData error
java.lang.IllegalStateException: **The specified child already has a parent. You must call removeView() on the child's parent first.**
at android.view.ViewGroup.addViewInner(ViewGroup.java:4315)
at android.view.ViewGroup.addView(ViewGroup.java:4151)
at android.view.ViewGroup.addView(ViewGroup.java:4123)
at com.way.heard.ui.views.NineGridImageView.setImagesData(NineGridImageView.java:155)
at com.way.heard.ui.activities.WritingActivity$7.onHanlderSuccess(WritingActivity.java:286)
at cn.finalteam.galleryfinal.PhotoBaseActivity.resultData(PhotoBaseActivity.java:186)
at cn.finalteam.galleryfinal.PhotoSelectActivity.onClick(PhotoSelectActivity.java:390)
at android.view.View.performClick(View.java:5226)
at android.view.View$PerformClick.run(View.java:21265)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:168)
at android.app.ActivityThread.main(ActivityThread.java:5845)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)
```

等我解决了过来Comment一下。

---

来了，**mImgDataList**的值会莫名其妙的丢失，导致
`mImgDataList.size() = 0;`
好在博主方法里也没用到**mImgDataList**里的数据，只用到了**size()**，用一个静态变量保存一下**size()**的值即可。

**Comment by laobie** [comment]
@WaylanPunch 怎么回事？是代码错误不？

**Comment by WaylanPunch** [comment]
@laobie mImgDataList似乎没有保留旧数据，所以首次绘图能展示，再次就不行了，至于什么时候被清空的我也不清楚了，你可以用你的代码做个测试，可能仅仅是我出现这个情况

**Comment by laobie** [comment]
看了下代码确实是这样的，同一个一直赋值的话是会导致这个错误的，因为一开始的使用场景是在列表中的，你的这种情况下，只能自己改下源代码，默认先 `removeAllView()` 一下
